### ISSUE TITLE
Visual problem with data view inside of datasource container

### ISSUE THREAD

**Issue by djut28** [Itvisors/mendix-ReactDnD#1] opened 2021-10-19 12:42 UTC
Hi there,
i have a problem to use a dataview inside a column/row datasource container. When i drag an object with a data view inside of it and stop it without really dropping it inside another container, the dataview enties are vanished.
Do you know this problem and can it be solved?

Thanks in advance and by the way, really nice widget, thanks for that anyway.

**Comment by mgroeneweg** [comment] 2021-10-19 17:04
[itvisors.MendixReactDnD.zip](https://github.com/Itvisors/mendix-ReactDnD/files/7375362/itvisors.MendixReactDnD.zip)
Hi,

Could you try with the attached version to see whether it makes a difference? If it makes no difference, please provide a test project with data and steps to reproduce the issue.

Which Mendix version are you using?

With regards,

Marcel

**Comment by djut28** [comment] 2021-10-20 07:19
Hi,
thanks for the quick response. Unfortunately the attached version did also not fix the issue. I use Mendix 9.6.
Here is a test version with the issue.
If you start to drag an object and stop without dropping it in a container the infos of the dataview are vanishing.

[DaDTestApp.zip](https://github.com/Itvisors/mendix-ReactDnD/files/7378956/DaDTestApp.zip)

Thanks for your help
Kind regards,
Chris

**Comment by mgroeneweg** [comment] 2021-10-21 05:17
Hi,

I am about to update the widget to 9.6. I hope next week. I will check your use case then as well.

With regards,

Marcel

**Comment by mgroeneweg** [comment] 2021-11-02 08:13
Hi,

I looked into the issue and I think it is caused by the dataview over association that is in the widget item. I'm afraid this is actually a bug in the datasource API but it will be really hard to convince Mendix support.

As an alternative, my advice would be to de-normalize the data in your database, so when creating the WorkStep objects, duplicate the other info. Or create another flat entity that holds only the data to display and the associations to the actual entity. Good chance either option would improve performance too.

Edit: I tried adding the WorkStep state to the page and that vanishes too. I will try with my test cases to see what happens. If I can fix it in the widget I will. 

With regards,

Marcel

**Comment by mgroeneweg** [comment] 2021-11-02 08:20
As an alternative: the test app shows a taskboard, do you know I created another widget just for that purpose? The ReactDnD might be a bit overkill for the use case. The TaskBoard widget wraps another library, published by the Atlassian Jira team.
[Widget](https://marketplace.mendix.com/link/component/116467)
[Demo](https://marketplace.mendix.com/link/component/116477)

**Comment by mgroeneweg** [comment] 2021-11-02 08:33
I have tried with my test project (The demo app that can be downloaded from Market Place). The basic tests work fine when doing an invalid drop. The floorplan demo had the same issue when dragging an item from the toolbar somewhere outside the floorplan, the item vanished. In this case I could solve it by removing the dataview over association and putting the association in the image viewer itself.

In your test app I made the same change and then it works correctly.
![image](https://user-images.githubusercontent.com/6723899/139812182-f11fcfe2-a4c8-41f6-8e3b-58f6b77d9cff.png)

The texts now appear with a white background but that can easily be fixed with a little styling changes.

**Comment by mgroeneweg** [comment] 2021-11-04 06:24
I received confirmation that the issue is indeed a Mendix 9 bug. Mendix R&D is investigating the issue. It can also happen on the DataGrid 2 widget. To avoid waiting on a fix, you could use the workaround I mentioned earlier: make each widget access the attribute over the association. This is not an issue with the widget, but I will keep the issue open anyway to post updates I receive from Mendix R&D

**Comment by djut28** [comment] 2021-11-04 10:39
Hi, thanks for all the support and the information. I will use a workaround. Thanks for the nice widget.

**Comment by mgroeneweg** [comment] 2022-01-16 07:33
Issue will be solved with Mendix 9.10. I tested with the beta and it works fine.

**Closed as completed by mgroeneweg** 2022-01-16 07:33 UTC
